# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 23:35
from __future__ import unicode_literals

import apps.vuivcl.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IM', 'IMAGE'), ('YO', 'YOUTUBE'), ('GI', 'GIF')], default='IM', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.vuivcl.models.upload_location)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('post_type', models.CharField(choices=[('IM', 'IMAGE'), ('YO', 'YOUTUBE'), ('GI', 'GIF')], default=None, max_length=2)),
                ('viewed_number', models.IntegerField()),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuivcl.Category')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date', '-updated_date'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuivcl.Post'),
        ),
    ]
