# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuivcl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
