# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 16:36
from __future__ import unicode_literals

import apps.vuivcl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuivcl', '0003_media_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='gif',
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.vuivcl.models.upload_location),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('IM', 'IMAGE'), ('YO', 'YOUTUBE'), ('VI', 'VIDEO')], default='IM', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('IM', 'IMAGE'), ('YO', 'YOUTUBE'), ('VI', 'VIDEO')], default=None, max_length=2),
        ),
    ]
