# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuivcl', '0004_auto_20170208_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('IM', 'IMAGE'), ('YO', 'YOUTUBE'), ('VI', 'VIDEO'), ('GI', 'GIF')], default='IM', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('IM', 'IMAGE'), ('YO', 'YOUTUBE'), ('VI', 'VIDEO'), ('GI', 'GIF')], default=None, max_length=2),
        ),
    ]
