# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 17:18
from __future__ import unicode_literals

import apps.vuivcl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuivcl', '0005_auto_20170208_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to=apps.vuivcl.models.upload_location),
        ),
    ]
